//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace newagenda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class appointments
    {
        public int idAppointment { get; set; }

        // Définition du Name de l'attribue
        [DisplayName("Date / Heure")]
        // Message d'erreur en cas de non saisie de utilisateur
        [Required(ErrorMessage = "Veuillez selectionner une date")]
        // Définition du datatype en datetime
        [DataType(DataType.DateTime)]
        // Affichage du format définie
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime datehour { get; set; }

        public DateTime dateHour { get; set; }
        [DisplayName("Sujet du rendez-vous")]
        public string subject { get; set; }

        [DisplayName("Nom / Prénom du client")]
        [Required(ErrorMessage = "Veuillez selectionner un client")]
        public int idBrokers { get; set; }

        [DisplayName("Nom / Prénom du courtier")]
        [Required(ErrorMessage = "Veuillez selectionner un courtier")]
        public int idCustomers { get; set; }
    
        public virtual brokers brokers { get; set; }
        public virtual customers customers { get; set; }
    }
}
